script:
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service // ThienNLNT
# Use either `docker-compose` or individual `docker build` commands // ThienNLNT
# Build // ThienNLNT
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
# Tagging // ThienNLNT
  - docker tag udagram-api-feed thiencoder/udagram-api-feed:v1
  - docker tag udagram-api-user thiencoder/udagram-api-user:v1
  - docker tag udagram-frontend thiencoder/udagram-frontend:v1
  - docker tag udagram-reverseproxy thiencoder/udagram-reverseproxy:v1
# Do similar for other three images``` // ThienNLNT
# Push // ThienNLNT
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings // ThienNLNT
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thiencoder/udagram-api-feed:v1
  - docker push thiencoder/udagram-api-user:v1
  - docker push thiencoder/udagram-frontend:v1
  - docker push thiencoder/udagram-reverseproxy:v1